# Hokuyo UTM-30LX laser scanner
# Pomerleau, F.; Breitenmoser, A; Ming Liu; Colas, F.; Siegwart, R.,
# "Noise characterization of depth sensors for surface inspections,"
# International Conference on Applied Robotics for the Power Industry (CARPI), 2012.

sensor_processor/type: laser
sensor_processor/min_radius: 0.018
sensor_processor/beam_angle: 0.0006
sensor_processor/beam_constant: 0.0015
sensor_processor/ignore_points_above: 1.0
sensor_processor/ignore_points_below: -0.4
