point_cloud_topic: "/move_group_scan_cloud"
map_frame_id: "world"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "/pose_cov"
robot_pose_cache_size: 200
track_point_frame_id: "base_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 0.5
time_tolerance: 0.5
